### ISSUE TITLE
Form Validation functionality in React

### ISSUE THREAD

**Issue by Amishakumari544** [Amishakumari544/Frontend_Resources#8]

**Comment by Athi223** [comment]
I'd like to contribute to this.

Could you give a brief idea of what is expected in it?
This is what I could guess from it: A single page form with few fields, validating each input as it is being entered & finally a submit button that could (for now) just display the entered data to console/alert assuming everything gets validated.

Also is any UI required? Or a plain HTML form is enough?

**Comment by Amishakumari544** [comment]
Yes, but no html form should only be react you can use react hook forms for the validation part.

**Comment by Athi223** [comment]
@Amishakumari544 Oh okay so I need to create a full React project right?

**Comment by Amishakumari544** [comment]
For a small button also you have to create whole react project even one line of text also. So yes!

**Comment by Athi223** [comment]
@Amishakumari544 Done, please review.
